# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14440401ed17720f7fba8eb5aa8714a35fef9b97464869ac93ef9d3dcc69cfb3f655e2fc8248819fd71366664f077ccaa73dd3a560280fc86ab0361175909d1c

test:
  secret_key_base: 193bdd76d78ae2ed438090916503f84d1032ded73c0e4f7729215bfcb159d11cdff72086e057a099d7c311267e94aa6a2e025251b6aae0ffc44a81a178efd678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
